version: "3.7"
services:
  spring-boot-mysql:
    image: spring-boot-mysql
    ports:
      - "8090:8090"
    expose:
      - "8090"
    container_name: spring-boot-mysql
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spring-boot-mysql
    depends_on:
      - mysql_container_spring
    restart: always
    environment:
      WAIT_HOSTS: mysql:3306

  mysql_container_spring:
    image: mysql:8
    restart: on-failure
    container_name: mysql_container_spring
    networks:
      - spring-boot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mcaprateek2013#
      - MYSQL_DATABASE=testDB
      - MYSQL_ROOT_USER=root
    ports:
    - "6033:3306"

networks:
  spring-boot-mysql: